spec:
  template:
    spec:
      # Declare a volume mounting the config map
      volumes:
        - configMap:
            # Name of the config map
            name: app-config
            optional: true
            # Define the items from the config map to mount
            items:
            - key: app-config.yml
              path: app-config.yml
            # Volume name (used as reference below)
          name: config
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: VERTX_CONFIG_PATH
              value: '/deployments/config/app-config.yml'
            - name: SENTIMENT_APIKEY
              valueFrom:
                secretKeyRef:
                  key: apikey
                  name: sentiment-api-key
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.disableDnsResolver=true'              
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: accesstoken
                  name: twitter-access-token
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: accesstokensecret
                  name: twitter-access-token-secret
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: consumerkey
                  name: twitter-consumer-key
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: consumersecret
                  name: twitter-consumer-secret
          volumeMounts:
            - name: config
              mountPath: /deployments/config
